### PR TITLE
Enable toStatus of DEBUG node.

### PR DESCRIPTION
**Pull request by ralphwetzel**
This small PR adds functionality to allow `toStatus` debugging of the `Debug` node.

### CODE REVIEW

**Comment by phoddie** [comment]
@ralphwetzel – The PR looks good. FWIW – I am trying not to carry references to `config`, because it allows for some code size optimizations in time. I would prefer to just copy the value of `tostatus`. I will update that after merging.

To merge, I do need to ask you to complete a [Moddable CLA](https://github.com/Moddable-OpenSource/moddable/tree/public/licenses#contributor-license-agreement) (which is basically the Google CLA). You can just email a signed copy of the [Individual CLA](https://github.com/Moddable-OpenSource/moddable/blob/public/licenses/Moddable%20CLA%20-%20individual.pdf) to `info@moddable.com`. Thank you.

**Comment by ralphwetzel** [comment]
I've updated the node to follow your guidance & as well to mimic closer the NR template. That said, there's still a huge difference between the two implementations...

**Comment by phoddie** [comment]
> I've updated the node to follow your guidance...

Cool. Thank you.

> ...& as well to mimic closer the NR template. That said, there's still a huge difference between the two implementations...

No doubt! I've been reading the Node-RED built-in nodes. It would be impractical to implement them in the same way for an MCU. I understand why the full Node-RED implementation is the way it is.  But, for the MCU there will inevitably be  constraints. Fortunately the MCU doesn't have to do all the same things as the full Node-RED either, so that helps.

**Comment by ralphwetzel** [comment]
> Fortunately the MCU doesn't have to do all the same things as the full Node-RED either, so that helps.

To abstract things a bit - using the example of the debug node:

- There's functionality that is necessary to run the flow. This functionality has to be implemented on the MCU side.
- There's functionality that is used to provide whatever kind of feedback in the editor. This functionality could (should?) be delegated to e.g. the plugin.


Transferring this principle to the topic of `.tostatus`, its functionality is mainly used to feedback (exemption: the `status` node). Rather than trying now to mimic the full behaviour of the NR node in MCU, raw data could be sent back to the NR runtime & received e.g. by the plugin. All the _expensive_ processing necessary just for feedback could then be done there...

**Comment by phoddie** [comment]
@ralphwetzel – agreed.. Those are two good points. Another one is that the Node-RED editor allows incremental deploy – unchanged nodes keep running while changed are replaced. That feature debatable for the MCU and it actually has quite a high runtime cost (though acceptable on a fast computer!). My early work intended to support that, but I am ready to declare it unnecessary for the MCU and remove that code.

**Comment by ralphwetzel** [comment]
> unchanged nodes keep running while changed are replaced.

As of now, I would prefer to just re-build the MCU app in total. Managing the diff between two build operations looks like a lot of overhead to me - for no real value add I can imagine.

**Pull request merged**
