### PR TITLE
Edit Range Node

### PR DESCRIPTION
**Pull request by mtoko**
I have added the code for (Scale and Limit) and (Scale and Wrap). Please check carefully before merging!

### CODE REVIEW

**Comment by phoddie** [comment]
Thank you for the PR. I'm going to try to build a flow to compare the output of this implementation and full Node-RED, since our goal is to match that behavior.

**Comment by phoddie** [comment]
Good news. The results with all three modes match Node-RED exactly. Very nice.

The original implementation precomputed `#scale` which avoids some duplicate calculation on each message. I'd prefer to keep that since it is a little smaller and faster. If you can put that back, great. If not, I can take care of it too after merging.

FWIW – to test more easily, I implemented part of Split (that's committed to this repository). Here's the flow I used to test.

<details>
<summary>Range test</summary>

```json
[
    {
        "id": "6f0d91d05788a23f",
        "type": "tab",
        "label": "filter",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "eb892643e0ec54af",
        "type": "debug",
        "z": "6f0d91d05788a23f",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": true,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 660,
        "y": 160,
        "wires": []
    },
    {
        "id": "717f9e04acca140a",
        "type": "split",
        "z": "6f0d91d05788a23f",
        "name": "",
        "splt": ", ",
        "spltType": "str",
        "arraySplt": "1",
        "arraySpltType": "len",
        "stream": false,
        "addname": "topic",
        "x": 350,
        "y": 160,
        "wires": [
            [
                "b40e8a97d7150373"
            ]
        ]
    },
    {
        "id": "9881dbf53a3eec76",
        "type": "inject",
        "z": "6f0d91d05788a23f",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": true,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "[-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]",
        "payloadType": "json",
        "x": 210,
        "y": 160,
        "wires": [
            [
                "717f9e04acca140a"
            ]
        ]
    },
    {
        "id": "b40e8a97d7150373",
        "type": "range",
        "z": "6f0d91d05788a23f",
        "minin": "0",
        "maxin": "10",
        "minout": "0",
        "maxout": "100",
        "action": "roll",
        "round": true,
        "property": "payload",
        "name": "",
        "x": 500,
        "y": 160,
        "wires": [
            [
                "eb892643e0ec54af"
            ]
        ]
    }
]
```

</details>

**Comment by mtoko** [comment]
Thanks, please add the modification you have suggested, this will be quicker than you testing again if I make the changes

**Comment by phoddie** [comment]
Sure, no problem. Once the CLA is complete, I'll merge this.

**Comment by mtoko** [comment]
CLA completed and sent to info@moddable.com

**Pull request merged**
