### PR TITLE
MCU Builder node: Initial commit.

### PR DESCRIPTION
**Pull request by ralphwetzel**
This is the initial attempt to support / automate the `node-red-mcu` building process.
This PR proposes a `MCU builder` node that is able to perform the building process from the `node-red` editor.
Minimal usecase:
image

The build parameters can either be provided as a parameter in `msg.mcu` or defined in the node config panel:

image

A short description of how to install this package was added to the readme.

No intensive testing has been performed ... thus: Expect the unexpected! :wink:

### CODE REVIEW

**Comment by phoddie** [comment]
Interesting idea to integrate this as a node. I'm excited to try this out. After doing the `npm install`, I get this error launching Node-RED.

```
10 Jul 22:55:58 - [warn] [node-red-contrib-mcu/mcu] Error: Cannot find module 'fs-extra'
Require stack:
- /Users/hoddie/Downloads/node-red-mcu-main/mcu.js
```

Maybe it is just a dependency problelm?

**Comment by ralphwetzel** [comment]
I was unsure, if that was necessary - yet it seem to be (once):
```
cd <path to your cloned directory>
npm install
```

**Comment by phoddie** [comment]
I'm getting closer. ;)

When running the flow, I get this error:

```
11 Jul 12:16:44 - [error] [node-red-mcu:2226b30fe881e9d5] TypeError: Cannot read properties of undefined (reading 'flows')
```

Here' the flow set-up:

image

I created an empty directory for the working directory at `node-red-mcu-test`. Is that correct?

**Comment by ralphwetzel** [comment]
> I‘ll check if I can locate the issue you encountered…

Ok. I think I found the issue. As a workaround, please inject an empty object `msg.mcu` via the inject node. I‘ll provide a fix later this week.

**Comment by phoddie** [comment]
@ralphwetzel – that works! Very nice.

The "working directory" is where you create the Moddable SDK project.

I'm not sure what "Create Build Environment" does. I haven't had a chance to read your sources yet to understand what it does.

**Comment by ralphwetzel** [comment]
If you uncheck the option "Create Build Environment", only `flows.js` will be created (in the working directory) - yet the rest of the files not.

**Comment by ralphwetzel** [comment]
As of now, the dialog matches the description you provided to build projects for XS. I agree, that it's currently quite technical - yet as well ultimately flexible. For the time being, I would like to focus on adding functionality ... knowing there's plentitude of opportunities to make things nicer.
That said, I propose to merge things as they are for now & put your valid comments on the ToDo-List.

**Comment by phoddie** [comment]
That's fine. I would prefer not to make the root of the node-red-mcu project specifically for the MCU builder. Maybe that is the right answer in the long term, but it seems too early to make that assumption. the `nodes` directory is for nodes that run on the MCU. What do you think about moving the content of this PR to `tools/mcubuilder`? It is pretty easy to imagine that there will be other tools eventually.

**Comment by ralphwetzel** [comment]
You're right. In the end, my proposal is just one way to integrate this idea into the NR editor. Thus I'll close this PR & keep things seperated - to not create too much interference.

**Comment by phoddie** [comment]
> ...my proposal is just one way to integrate this idea into the NR editor. Thus I'll close this PR & keep things separated - to not create too much interference

I still think it would be good to have as part of this repository. It is useful and provides an example for others who may with to explore other approaches.

**Pull request closed without merging**
